INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (001,'001 - BANCO DO BRASIL S/A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (002,'002 - BANCO CENTRAL DO BRASIL',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (003,'003 - BANCO DA AMAZONIA S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (004,'004 - BANCO DO NORDESTE DO BRASIL S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (007,'007 - BANCO NAC DESENV. ECO. SOCIAL S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (008,'008 - BANCO MERIDIONAL DO BRASIL',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (020,'020 - BANCO DO ESTADO DE ALAGOAS S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (021,'021 - BANCO DO ESTADO DO ESPIRITO SANTO S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (022,'022 - BANCO DE CREDITO REAL DE MINAS GERAIS SA',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (024,'024 - BANCO DO ESTADO DE PERNAMBUCO',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (025,'025 - BANCO ALFA S/A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (026,'026 - BANCO DO ESTADO DO ACRE S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (027,'027 - BANCO DO ESTADO DE SANTA CATARINA S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (028,'028 - BANCO DO ESTADO DA BAHIA S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (029,'029 - BANCO DO ESTADO DO RIO DE JANEIRO S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (030,'030 - BANCO DO ESTADO DA PARAIBA S.A',9.40, 8.45, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (031,'031 - BANCO DO ESTADO DE GOIAS S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (032,'032 - BANCO DO ESTADO DO MATO GROSSO S.A.',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (033,'033 - BANCO DO ESTADO DE SAO PAULO S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (034,'034 - BANCO DO ESADO DO AMAZONAS S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (035,'035 - BANCO DO ESTADO DO CEARA S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (036,'036 - BANCO DO ESTADO DO MARANHAO S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (037,'037 - BANCO DO ESTADO DO PARA S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (038,'038 - BANCO DO ESTADO DO PARANA S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (039,'039 - BANCO DO ESTADO DO PIAUI S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (041,'041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (047,'047 - BANCO DO ESTADO DE SERGIPE S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (048,'048 - BANCO DO ESTADO DE MINAS GERAIS S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (059,'059 - BANCO DO ESTADO DE RONDONIA S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (066,'066 - BANCO MORGAN STANLEY S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (070,'070 - BANCO DE BRASILIA S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (077,'077 - BANCO DE INTER S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (104,'104 - CAIXA ECONOMICA FEDERAL',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (106,'106 - BANCO ITABANCO S.A.',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (107,'107 - BANCO BBM S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (109,'109 - BANCO CREDIBANCO S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (116,'116 - BANCO B.N.L DO BRASIL S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (129,'129 - UBS BRASIL BANCO DE INVESTIMENTO S.A.',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (148,'148 - MULTI BANCO S.A',7.40, 9.75, 0,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (151,'151 - CAIXA ECONOMICA DO ESTADO DE SAO PAULO',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (153,'153 - CAIXA ECONOMICA DO ESTADO DO R.G.SUL',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (165,'165 - BANCO NORCHEM S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (166,'166 - BANCO INTER-ATLANTICO S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (168,'168 - BANCO C.C.F. BRASIL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (175,'175 - CONTINENTAL BANCO S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (184,'184 - BBA - CREDITANSTALT S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (199,'199 - BANCO FINANCIAL PORTUGUES',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (200,'200 - BANCO FRICRISA AXELRUD S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (201,'201 - BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (204,'204 - BANCO S.R.L S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (205,'205 - BANCO SUL AMERICA S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (206,'206 - BANCO MARTINELLI S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (208,'208 - BANCO PACTUAL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (210,'210 - DEUTSCH SUDAMERIKANICHE BANK AG',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (211,'211 - BANCO SISTEMA S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (212,'212 - BANCO ORIGINAL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (213,'213 - BANCO ARBI S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (214,'214 - BANCO DIBENS S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (215,'215 - BANCO AMERICA DO SUL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (216,'216 - BANCO REGIONAL MALCON S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (217,'217 - BANCO AGROINVEST S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (218,'218 - BBS - BANCO BONSUCESSO S.A.',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (219,'219 - BANCO DE CREDITO DE SAO PAULO S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (220,'220 - BANCO CREFISUL',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (221,'221 - BANCO GRAPHUS S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (222,'222 - BANCO AGF BRASIL S. A.',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (223,'223 - BANCO INTERUNION S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (224,'224 - BANCO FIBRA S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (225,'225 - BANCO BRASCAN S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (228,'228 - BANCO ICATU S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (229,'229 - BANCO CRUZEIRO S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (230,'230 - BANCO BANDEIRANTES S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (231,'231 - BANCO BOAVISTA S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (232,'232 - BANCO INTERPART S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (233,'233 - BANCO MAPPIN S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (234,'234 - BANCO LAVRA S.A.',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (235,'235 - BANCO LIBERAL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (236,'236 - BANCO CAMBIAL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (237,'237 - BANCO BRADESCO S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (239,'239 - BANCO BANCRED S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (240,'240 - BANCO DE CREDITO REAL DE MINAS GERAIS S.',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (241,'241 - BANCO CLASSICO S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (242,'242 - BANCO EUROINVEST S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (243,'243 - BANCO STOCK S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (244,'244 - BANCO CIDADE S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (245,'245 - BANCO EMPRESARIAL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (246,'246 - BANCO ABC ROMA S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (247,'247 - BANCO OMEGA S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (249,'249 - BANCO INVESTCRED S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (250,'250 - BANCO SCHAHIN CURY S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (251,'251 - BANCO SAO JORGE S.A.',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (252,'252 - BANCO FININVEST S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (254,'254 - BANCO PARANA BANCO S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (255,'255 - MILBANCO S.A.',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (256,'256 - BANCO GULVINVEST S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (258,'258 - BANCO INDUSCRED S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (260,'260 - NU PAGAMENTOS S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (261,'261 - BANCO VARIG S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (262,'262 - BANCO BOREAL S.A',7.40, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (263,'263 - BANCO CACIQUE',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (264,'264 - BANCO PERFORMANCE S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (265,'265 - BANCO FATOR S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (266,'266 - BANCO CEDULA S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (267,'267 - BANCO BBM-COM.C.IMOB.CFI S.A.',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (275,'275 - BANCO REAL S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (277,'277 - BANCO PLANIBANC S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (282,'282 - BANCO BRASILEIRO COMERCIAL',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (291,'291 - BANCO DE CREDITO NACIONAL S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (294,'294 - BCR - BANCO DE CREDITO REAL S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (295,'295 - BANCO CREDIPLAN S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (300,'300 - BANCO DE LA NACION ARGENTINA S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (302,'302 - BANCO DO PROGRESSO S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (303,'303 - BANCO HNF S.A.',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (304,'304 - BANCO PONTUAL S.A',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (308,'308 - BANCO COMERCIAL BANCESA S.A.',9.80, 9.75, 1,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (318,'318 - BANCO B.M.G. S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (320,'320 - BANCO INDUSTRIAL E COMERCIAL',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (341,'341 - BANCO ITAU S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (346,'346 - BANCO FRANCES E BRASILEIRO S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (347,'347 - BANCO SUDAMERIS BRASIL S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (351,'351 - BANCO BOZANO SIMONSEN S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (353,'353 - BANCO GERAL DO COMERCIO S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (356,'356 - ABN AMRO S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (366,'366 - BANCO SOGERAL S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (369,'369 - PONTUAL',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (370,'370 - BEAL - BANCO EUROPEU PARA AMERICA LATINA',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (372,'372 - BANCO ITAMARATI S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (375,'375 - BANCO FENICIA S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (376,'376 - CHASE MANHATTAN BANK S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (388,'388 - BANCO MERCANTIL DE DESCONTOS S/A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (389,'389 - BANCO MERCANTIL DO BRASIL S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (392,'392 - BANCO MERCANTIL DE SAO PAULO S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (394,'394 - BANCO B.M.C. S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (399,'399 - HSBC BANK BRASIL S.A. – BANCO MÚLTIPLO',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (409,'409 - UNIBANCO - UNIAO DOS bank BRASILEIROS',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (412,'412 - BANCO NACIONAL DA BAHIA S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (415,'415 - BANCO NACIONAL S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (420,'420 - BANCO NACIONAL DO NORTE S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (422,'422 - BANCO SAFRA S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (424,'424 - BANCO NOROESTE S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (434,'434 - BANCO FORTALEZA S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (453,'453 - BANCO RURAL S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (456,'456 - BANCO TOKIO S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (464,'464 - BANCO SUMITOMO BRASILEIRO S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (466,'466 - BANCO MITSUBISHI BRASILEIRO S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (472,'472 - LLOYDS BANK PLC',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (473,'473 - BANCO FINANCIAL PORTUGUES S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (477,'477 - CITIBANK N.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (479,'479 - BANCO DE BOSTON S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (480,'480 - BANCO PORTUGUES DO ATLANTICO-BRASIL S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (483,'483 - BANCO AGRIMISA S.A.',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (487,'487 - DEUTSCHE BANK S.A - BANCO ALEMAO',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (488,'488 - BANCO J. P. MORGAN S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (489,'489 - BANESTO BANCO URUGAUAY S.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (492,'492 - INTERNATIONALE NEDERLANDEN BANK N.V.',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (493,'493 - BANCO UNION S.A.C.A',9.80, 9.75, 2,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (494,'494 - BANCO LA REP. ORIENTAL DEL URUGUAY',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (495,'495 - BANCO LA PROVINCIA DE BUENOS AIRES',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (496,'496 - BANCO EXTERIOR DE ESPANA S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (498,'498 - CENTRO HISPANO BANCO',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (499,'499 - BANCO IOCHPE S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (501,'501 - BANCO BRASILEIRO IRAQUIANO S.A.',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (502,'502 - BANCO SANTANDER S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (504,'504 - BANCO MULTIPLIC S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (505,'505 - BANCO GARANTIA S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (600,'600 - BANCO LUSO BRASILEIRO S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (601,'601 - BFC BANCO S.A.',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (602,'602 - BANCO PATENTE S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (604,'604 - BANCO INDUSTRIAL DO BRASIL S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (607,'607 - BANCO SANTOS NEVES S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (608,'608 - BANCO OPEN S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (610,'610 - BANCO V.R. S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (611,'611 - BANCO PAULISTA S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (612,'612 - BANCO GUANABARA S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (613,'613 - BANCO PECUNIA S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (616,'616 - BANCO INTERPACIFICO S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (617,'617 - BANCO INVESTOR S.A.',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (618,'618 - BANCO TENDENCIA S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (621,'621 - BANCO APLICAP S.A.',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (622,'622 - BANCO DRACMA S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (623,'623 - BANCO PANAMERICANO S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (624,'624 - BANCO GENERAL MOTORS S.A',9.80, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (625,'625 - BANCO ARAUCARIA S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (626,'626 - BANCO FICSA S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (627,'627 - BANCO DESTAK S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (628,'628 - BANCO CRITERIUM S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (629,'629 - BANCORP BANCO COML. E. DE INVESTMENTO',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (630,'630 - BANCO INTERCAP S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (633,'633 - BANCO REDIMENTO S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (634,'634 - BANCO TRIANGULO S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (635,'635 - BANCO DO ESTADO DO AMAPA S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (637,'637 - BANCO SOFISA S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (638,'638 - BANCO PROSPER S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (639,'639 - BIG S.A. - BANCO IRMAOS GUIMARAES',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (640,'640 - BANCO DE CREDITO METROPOLITANO S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (641,'641 - BANCO EXCEL ECONOMICO S/A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (643,'643 - BANCO SEGMENTO S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (645,'645 - BANCO DO ESTADO DE RORAIMA S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (647,'647 - BANCO MARKA S.A',9.80, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (648,'648 - BANCO ATLANTIS S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (649,'649 - BANCO DIMENSAO S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (650,'650 - BANCO PEBB S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (652,'652 - ITAÚ UNIBANCO HOLDING S.A.',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (653,'653 - BANCO INDUSVAL S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (654,'654 - BANCO A. J. RENNER S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (655,'655 - BANCO VOTORANTIM S.A.',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (656,'656 - BANCO MATRIX S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (657,'657 - BANCO TECNICORP S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (658,'658 - BANCO PORTO REAL S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (702,'702 - BANCO SANTOS S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (705,'705 - BANCO INVESTCORP S.A.',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (707,'707 - BANCO DAYCOVAL S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (711,'711 - BANCO VETOR S.A.',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (713,'713 - BANCO CINDAM S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (715,'715 - BANCO VEGA S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (718,'718 - BANCO OPERADOR S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (719,'719 - BANCO PRIMUS S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (720,'720 - BANCO MAXINVEST S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (721,'721 - BANCO CREDIBEL S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (722,'722 - BANCO INTERIOR DE SAO PAULO S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (724,'724 - BANCO PORTO SEGURO S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (725,'725 - BANCO FINABANCO S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (726,'726 - BANCO UNIVERSAL S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (728,'728 - BANCO FITAL S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (729,'729 - BANCO FONTE S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (730,'730 - BANCO COMERCIAL PARAGUAYO S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (731,'731 - BANCO GNPP S.A.',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (732,'732 - BANCO PREMIER S.A.',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (733,'733 - BANCO NACOES S.A.',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (734,'734 - BANCO GERDAU S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (735,'735 - BACO POTENCIAL',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (736,'736 - BANCO UNITED S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (737,'737 - THECA',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (738,'738 - MARADA',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (739,'739 - BGN',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (740,'740 - BCN BARCLAYS',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (741,'741 - BRP',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (742,'742 - EQUATORIAL',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (743,'743 - BANCO EMBLEMA S.A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (744,'744 - THE FIRST NATIONAL BANK OF BOSTON',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (745,'745 - CITIBAN N.A.',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (746,'746 - MODAL S/A',9.40, 9.99, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (747,'747 - RAIBOBANK DO BRASIL',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (748,'748 - SICREDI',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (749,'749 - BRMSANTIL SA',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (750,'750 - BANCO REPUBLIC NATIONAL OF NEW YORK (BRA',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (751,'751 - DRESDNER BANK LATEINAMERIKA-BRASIL S/A',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (752,'752 - BANCO BANQUE NATIONALE DE PARIS BRASIL S',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (753,'753 - BANCO COMERCIAL URUGUAI S.A.',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (755,'755 - BANCO MERRILL LYNCH S.A',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (756,'756 - BANCO COOPERATIVO DO BRASIL S.A.',9.40, 9.75, 3,'ACTIVE');
INSERT INTO `bank` (`id_bank`, `name_bank`, `doc_fee`, `ted_fee`, `monthly_free_transfers`, `status_data_base`) VALUES (757,'757 - BANCO KEB DO BRASIL S.A.',9.40, 9.75, 3,'ACTIVE');