insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Acre','AC',1);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Alagoas','AL',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Amapá','AP',1);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Amazonas','AM',1);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Bahia','BA',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Ceará','CE',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Distrito Federal','DF',5);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Espírito Santo','ES',5);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Pará','PA',1);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Goiás','GO',5);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Maranhão','MA',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Mato Grosso','MT',5);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Mato Grosso do Sul','MS',4);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Minas Gerais','MG',3);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Paraíba','PB',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Paraná','PR',4);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Pernambuco','PE',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Piauí', 'PI',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Rio Grande do Norte','RN',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Rio Grande do Sul', 'RS',4);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Rondônia','RO',1);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Roraima','RR',1);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Santa Catarina','SC',4);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'São Paulo','SP', 3);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Sergipe','SE',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Tocantins','TO',2);
insert into state (id_state, name_state, acronym_state, rf_region) values (null,'Rio de Janeiro','RJ',3);
